# Generated by Django 5.1.6 on 2025-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tag',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
